export type CourseDetail = {
  slug: string;
  name: string;
  tagline: string;
  icon: string;
  iconBg: string;
  iconColor: string;
  overview: string;
  objectives: string[];
  duration: string;
  format: string;
  level: string;
  price: string;
  installment: string;
  curriculum: { week: string; topic: string; details: string }[];
  projects: string[];
  careers: { role: string; salary: string }[];
  certification: string;
  faqs: { q: string; a: string }[];
  related: string[]; // other slugs
};

export const COURSES: CourseDetail[] = [
  {
    slug: "python-programming",
    name: "Python Programming (Basic)",
    tagline: "Build a strong foundation in Python — from syntax to real automation scripts.",
    icon: "ti-brand-python",
    iconBg: "rgba(24,95,165,0.15)",
    iconColor: "#5BA4F5",
    overview:
      "This beginner-friendly Python programming track takes you from zero to writing your own scripts and small applications. You'll learn how computers think, how to write clean, readable code, and how to automate boring tasks — the same foundation used in web development, data science, AI and cyber security.",
    objectives: [
      "Understand core programming concepts: variables, data types, logic and flow control",
      "Write functions, work with lists, dictionaries and files",
      "Apply Object-Oriented Programming (classes and objects)",
      "Build small automation scripts and mini utility apps",
      "Debug code confidently and follow Python best practices",
    ],
    duration: "3 months (renewable per module)",
    format: "Hybrid — physical class in Ikorodu + live online sessions",
    level: "Beginner",
    price: "₦25,000 / month",
    installment: "Split payment available (50% upfront · 50% mid-month)",
    curriculum: [
      { week: "Week 1", topic: "Setup & Python Basics", details: "Install Python, VS Code. Variables, data types, input/output." },
      { week: "Week 2", topic: "Control Flow", details: "If/else, loops (for, while), boolean logic, small exercises." },
      { week: "Week 3", topic: "Functions & Modules", details: "Reusable code, arguments, return values, imports." },
      { week: "Week 4", topic: "Data Structures", details: "Lists, tuples, dictionaries, sets — real-world examples." },
      { week: "Week 5", topic: "Files & Errors", details: "Read/write files, try/except, working with CSV and JSON." },
      { week: "Week 6", topic: "OOP Foundations", details: "Classes, objects, inheritance, encapsulation." },
      { week: "Week 7", topic: "Automation Scripts", details: "Automate file renaming, PDF/Excel handling, web scraping intro." },
      { week: "Week 8", topic: "Capstone Project", details: "Build & present a small app of your choice with mentor review." },
    ],
    projects: [
      "Personal expense tracker (CLI)",
      "Bulk file organiser / renamer",
      "Simple web scraper for news headlines",
      "Password strength checker",
      "Capstone: mini app of your choice",
    ],
    careers: [
      { role: "Junior Python Developer", salary: "₦150,000 – ₦350,000 / month" },
      { role: "Automation / Scripting Engineer", salary: "₦200,000 – ₦450,000 / month" },
      { role: "Data / AI Track Entry Role", salary: "₦180,000 – ₦400,000 / month" },
      { role: "Freelance Python Developer", salary: "$15 – $40 / hour" },
    ],
    certification:
      "Glass Nexus Academy Certificate of Completion — awarded after finishing all modules and delivering a capstone project. Includes portfolio-ready projects on GitHub.",
    faqs: [
      { q: "Do I need any prior coding experience?", a: "No. This track is designed for complete beginners. If you can use a computer, you can start." },
      { q: "What laptop do I need?", a: "Any modern laptop with 4GB RAM or more will do. We help you set up the environment on day one." },
      { q: "Can I attend online?", a: "Yes. Every physical class is also streamed live, and recordings are shared in the student portal." },
      { q: "What happens after the 3 months?", a: "You can move into Data Analysis, AI & Automation, or Backend Web Development using Python as a base." },
    ],
    related: ["data-analysis", "web-design-backend", "ai-automation"],
  },
  {
    slug: "web-design-frontend",
    name: "Web Design — Frontend",
    tagline: "HTML, CSS and React — build modern, responsive websites and a real portfolio.",
    icon: "ti-world",
    iconBg: "rgba(14,165,233,0.15)",
    iconColor: "#0EA5E9",
    overview:
      "Learn to design and build the websites people actually use — from personal portfolios to business landing pages and dashboards. You'll master the modern frontend stack (HTML5, CSS3, JavaScript and React) with a heavy emphasis on responsive design, accessibility and clean UI.",
    objectives: [
      "Structure semantic HTML5 pages and forms",
      "Style with modern CSS: Flexbox, Grid, custom properties, animations",
      "Write interactive JavaScript (ES6+) and manipulate the DOM",
      "Build component-based UIs with React",
      "Deploy websites live to the internet",
    ],
    duration: "3 months",
    format: "Hybrid — physical + live online",
    level: "Beginner to Intermediate",
    price: "₦25,000 / month",
    installment: "Split payment available (50% upfront · 50% mid-month)",
    curriculum: [
      { week: "Week 1", topic: "HTML5 Foundations", details: "Semantic tags, forms, accessibility basics." },
      { week: "Week 2", topic: "CSS Layout", details: "Flexbox, Grid, responsive design, mobile-first." },
      { week: "Week 3", topic: "CSS Advanced", details: "Custom properties, transitions, animations, modern effects." },
      { week: "Week 4", topic: "JavaScript Basics", details: "Variables, functions, arrays, DOM manipulation." },
      { week: "Week 5", topic: "JavaScript ES6+", details: "Modules, promises, fetch API, async/await." },
      { week: "Week 6", topic: "React Fundamentals", details: "Components, props, state, hooks." },
      { week: "Week 7", topic: "Routing & Forms in React", details: "React Router, controlled forms, validation." },
      { week: "Week 8", topic: "Portfolio Project", details: "Ship a live personal portfolio + business landing page." },
    ],
    projects: [
      "Personal portfolio site",
      "Restaurant / business landing page",
      "Interactive product page with cart",
      "Weather / news dashboard consuming a public API",
      "Capstone: full multi-page React site deployed live",
    ],
    careers: [
      { role: "Junior Frontend Developer", salary: "₦180,000 – ₦450,000 / month" },
      { role: "React Developer", salary: "₦250,000 – ₦700,000 / month" },
      { role: "Freelance Web Designer", salary: "₦80,000 – ₦500,000 / project" },
      { role: "Remote Frontend (International)", salary: "$20 – $60 / hour" },
    ],
    certification:
      "Glass Nexus Academy Frontend Certificate + a live-deployed portfolio you can share with employers and clients.",
    faqs: [
      { q: "Will I really be able to build websites?", a: "Yes. Every module is project-based — you build as you learn, and you leave with a live portfolio." },
      { q: "Is React hard for beginners?", a: "We introduce it step by step after a solid JavaScript foundation, so it feels natural by the time you reach it." },
      { q: "Do you cover hosting?", a: "Yes — we deploy your projects live using free modern hosting (Vercel/Netlify) as part of the course." },
    ],
    related: ["web-design-backend", "ui-ux-video", "python-programming"],
  },
  {
    slug: "web-design-backend",
    name: "Web Design — Backend (PHP)",
    tagline: "Server-side PHP + MySQL — build dynamic websites and admin panels.",
    icon: "ti-server",
    iconBg: "rgba(83,74,183,0.15)",
    iconColor: "#9B8FFF",
    overview:
      "Go beyond static pages. Learn how the server side of the web really works — handling logins, databases, forms, uploads and admin dashboards using PHP and MySQL, the stack that powers a huge chunk of the internet.",
    objectives: [
      "Understand how HTTP, requests and responses work",
      "Write clean PHP: variables, functions, arrays, OOP",
      "Design and query MySQL databases",
      "Build authentication, forms, uploads and admin panels",
      "Secure your app against SQL injection and common attacks",
    ],
    duration: "3 months",
    format: "Hybrid — physical + live online",
    level: "Beginner to Intermediate",
    price: "₦25,000 / month",
    installment: "Split payment available",
    curriculum: [
      { week: "Week 1", topic: "How the Web Works", details: "Client vs server, PHP setup, first script." },
      { week: "Week 2", topic: "PHP Basics", details: "Syntax, variables, control flow, functions." },
      { week: "Week 3", topic: "Forms & Sessions", details: "Handle POST/GET, sessions, cookies." },
      { week: "Week 4", topic: "MySQL & PDO", details: "Design tables, CRUD queries, prepared statements." },
      { week: "Week 5", topic: "Authentication", details: "Registration, login, password hashing." },
      { week: "Week 6", topic: "File Uploads & Emails", details: "Handle uploads safely, send transactional emails." },
      { week: "Week 7", topic: "Admin Dashboard", details: "Protected routes, roles, data tables." },
      { week: "Week 8", topic: "Deployment & Security", details: "cPanel deploy, HTTPS, hardening." },
    ],
    projects: [
      "Blog with admin panel",
      "Student result portal",
      "E-commerce mini shop with cart & orders",
      "Multi-user dashboard with roles",
    ],
    careers: [
      { role: "Junior Backend Developer", salary: "₦200,000 – ₦500,000 / month" },
      { role: "PHP / Laravel Developer", salary: "₦250,000 – ₦700,000 / month" },
      { role: "Freelance Web App Developer", salary: "₦150,000 – ₦1,000,000 / project" },
    ],
    certification: "Glass Nexus Academy Backend Certificate + at least two deployed backend projects.",
    faqs: [
      { q: "Do I need to learn frontend first?", a: "Basic HTML/CSS helps, but we cover just enough at the start so you can focus on backend logic." },
      { q: "Why PHP and not Node?", a: "PHP still powers a huge share of live websites in Nigeria and globally — plenty of local jobs and freelance work." },
    ],
    related: ["web-design-frontend", "data-analysis", "cyber-security"],
  },
  {
    slug: "data-analysis",
    name: "Data Analysis",
    tagline: "Turn raw data into decisions with Advanced Excel and SQL.",
    icon: "ti-chart-bar",
    iconBg: "rgba(83,74,183,0.15)",
    iconColor: "#9B8FFF",
    overview:
      "One of the fastest-growing skills in the world. Learn to clean, analyse and visualise data using Advanced Excel and SQL — the two tools most analysts actually use every day — and communicate findings clearly to non-technical stakeholders.",
    objectives: [
      "Clean and prepare messy real-world data",
      "Master Excel: formulas, pivot tables, Power Query, dashboards",
      "Write SQL to query relational databases",
      "Design clear, honest charts and dashboards",
      "Tell a story with data",
    ],
    duration: "3 months",
    format: "Hybrid — physical + live online",
    level: "Beginner-friendly",
    price: "₦25,000 / month",
    installment: "Split payment available",
    curriculum: [
      { week: "Week 1", topic: "Data Thinking + Excel Basics", details: "Cells, formulas, formatting, keyboard workflow." },
      { week: "Week 2", topic: "Formulas & Functions", details: "IF, VLOOKUP/XLOOKUP, INDEX-MATCH, text/date functions." },
      { week: "Week 3", topic: "Pivot Tables & Charts", details: "Summarise, slice, and visualise data quickly." },
      { week: "Week 4", topic: "Power Query & Cleaning", details: "Import, merge, clean and transform datasets." },
      { week: "Week 5", topic: "SQL Foundations", details: "SELECT, WHERE, ORDER BY, JOINs." },
      { week: "Week 6", topic: "SQL Advanced", details: "GROUP BY, aggregate functions, subqueries." },
      { week: "Week 7", topic: "Dashboards", details: "Build an Excel dashboard and a SQL-backed report." },
      { week: "Week 8", topic: "Capstone", details: "Analyse a real dataset end-to-end and present findings." },
    ],
    projects: [
      "Sales performance dashboard in Excel",
      "HR attrition analysis with pivot tables",
      "SQL report over a sample e-commerce database",
      "Capstone data story presentation",
    ],
    careers: [
      { role: "Junior Data Analyst", salary: "₦200,000 – ₦500,000 / month" },
      { role: "Business / Operations Analyst", salary: "₦250,000 – ₦600,000 / month" },
      { role: "Freelance Analyst", salary: "$25 – $60 / hour" },
    ],
    certification: "Data Analysis Certificate + portfolio of Excel and SQL projects.",
    faqs: [
      { q: "Do I need to be good at maths?", a: "No — basic arithmetic is enough. The focus is on logic, curiosity and clear thinking." },
      { q: "Which SQL flavour do you teach?", a: "Standard SQL using MySQL/PostgreSQL — the skills transfer to any database." },
    ],
    related: ["python-programming", "computer-operations", "web-design-backend"],
  },
  {
    slug: "hardware-repairs",
    name: "Hardware & Repairs",
    tagline: "Diagnose and repair PCs, laptops and smartphones — 100% practical.",
    icon: "ti-cpu",
    iconBg: "rgba(186,117,23,0.15)",
    iconColor: "#F5C542",
    overview:
      "A hands-on, workshop-based track. You'll learn how computers and phones are actually built, how to diagnose common faults, and how to safely replace components — plus how to set up and run a small repair business.",
    objectives: [
      "Identify PC, laptop and smartphone components",
      "Diagnose hardware faults systematically",
      "Safely disassemble and reassemble devices",
      "Replace screens, batteries, RAM, storage and more",
      "Set up a repair workflow and pricing for customers",
    ],
    duration: "3 months",
    format: "Physical (Ikorodu lab) — practical every session",
    level: "Beginner",
    price: "Contact for fee",
    installment: "Split payment available",
    curriculum: [
      { week: "Week 1", topic: "Tools & Safety", details: "ESD safety, tools, workflow, workshop discipline." },
      { week: "Week 2", topic: "PC Internals", details: "CPU, RAM, storage, PSU, motherboard walkthrough." },
      { week: "Week 3", topic: "Laptop Teardown", details: "Full disassembly, cleaning, thermal paste." },
      { week: "Week 4", topic: "Common Faults", details: "No power, no display, overheating diagnostics." },
      { week: "Week 5", topic: "OS Install & Recovery", details: "Windows install, drivers, data recovery basics." },
      { week: "Week 6", topic: "Smartphone Repairs", details: "Screens, batteries, charging ports." },
      { week: "Week 7", topic: "Business Setup", details: "Pricing, invoicing, customer handling, marketing." },
      { week: "Week 8", topic: "Live Repairs", details: "Work on real customer devices under supervision." },
    ],
    projects: [
      "Full laptop teardown, cleaning and reassembly",
      "Windows reinstall + driver setup",
      "Phone screen replacement",
      "Business plan for a small repair shop",
    ],
    careers: [
      { role: "Hardware Technician", salary: "₦120,000 – ₦300,000 / month" },
      { role: "Repair Shop Owner", salary: "₦200,000 – ₦800,000 / month (business-dependent)" },
      { role: "IT Support Officer", salary: "₦150,000 – ₦350,000 / month" },
    ],
    certification: "Practical Hardware & Repairs Certificate — awarded after supervised live repairs.",
    faqs: [
      { q: "Do I need to bring my own tools?", a: "No — the lab is fully equipped. You can buy your own kit later once you're confident." },
      { q: "Is this class online?", a: "This one is physical only. You must handle real hardware to learn properly." },
    ],
    related: ["computer-operations", "cyber-security"],
  },
  {
    slug: "computer-operations",
    name: "Computer Operations (Microsoft Packages)",
    tagline: "Master computer fundamentals and Microsoft Office — Word, Excel, PowerPoint.",
    icon: "ti-device-desktop",
    iconBg: "rgba(14,165,233,0.15)",
    iconColor: "#0EA5E9",
    overview:
      "Perfect for students, job seekers and professionals who want real digital confidence. Learn how a computer works, how to use it productively, and how to master the Microsoft Office suite that most employers still test for.",
    objectives: [
      "Use Windows confidently — files, folders, shortcuts",
      "Type and format professional documents in Word",
      "Build spreadsheets, formulas and charts in Excel",
      "Design clean, engaging presentations in PowerPoint",
      "Use email, cloud storage and safe browsing",
    ],
    duration: "2 months",
    format: "Hybrid — physical + live online",
    level: "Beginner",
    price: "₦25,000 / month",
    installment: "Split payment available",
    curriculum: [
      { week: "Week 1", topic: "Computer & Windows Basics", details: "Hardware overview, files, folders, keyboard shortcuts." },
      { week: "Week 2", topic: "Microsoft Word", details: "Formatting, styles, tables, CVs, letters, reports." },
      { week: "Week 3", topic: "Excel Essentials", details: "Cells, formulas, functions, formatting." },
      { week: "Week 4", topic: "Excel Intermediate", details: "Charts, sorting/filtering, pivot tables intro." },
      { week: "Week 5", topic: "PowerPoint", details: "Slide design, transitions, professional presentations." },
      { week: "Week 6", topic: "Internet & Productivity", details: "Email, Google Drive, safe browsing, printing." },
      { week: "Week 7", topic: "Project", details: "Build a full CV, budget spreadsheet, and pitch deck." },
      { week: "Week 8", topic: "Practice & Certification", details: "Assessment and portfolio finalisation." },
    ],
    projects: [
      "Professional CV in Word",
      "Personal / business budget in Excel",
      "Pitch deck in PowerPoint",
      "Digital filing system on your laptop",
    ],
    careers: [
      { role: "Office / Admin Assistant", salary: "₦80,000 – ₦200,000 / month" },
      { role: "Data Entry Officer", salary: "₦80,000 – ₦180,000 / month" },
      { role: "Front Desk / Executive Assistant", salary: "₦100,000 – ₦250,000 / month" },
    ],
    certification: "Microsoft Packages Certificate — recognised for entry-level office roles.",
    faqs: [
      { q: "I've never used a computer — can I still join?", a: "Absolutely. We start from turning the computer on. This is the perfect first course." },
      { q: "Can I use my phone instead of a laptop?", a: "You'll need access to a laptop for Excel/Word practice. If you don't have one, we have systems at the physical lab." },
    ],
    related: ["data-analysis", "python-programming", "hardware-repairs"],
  },
  {
    slug: "ai-automation",
    name: "AI & Automation",
    tagline: "Use AI tools and no-code automation to work 10x faster.",
    icon: "ti-robot",
    iconBg: "rgba(255,140,66,0.15)",
    iconColor: "#FF8C42",
    overview:
      "AI is changing how work gets done. In this track you'll learn to use modern AI tools (ChatGPT, Claude, image and video AI) and automation platforms (Zapier, Make, n8n) to build real workflows — for yourself, for a business, or as a paid service.",
    objectives: [
      "Prompt AI models effectively for real tasks",
      "Automate repetitive workflows without heavy coding",
      "Build AI-powered content, research and support flows",
      "Integrate AI with WhatsApp, email, Sheets and websites",
      "Understand safety, ethics and limits of AI",
    ],
    duration: "2 months",
    format: "Hybrid — physical + live online",
    level: "Beginner-friendly",
    price: "₦25,000 / month",
    installment: "Split payment available",
    curriculum: [
      { week: "Week 1", topic: "AI Foundations", details: "How LLMs work in plain English, capabilities & limits." },
      { week: "Week 2", topic: "Prompt Engineering", details: "Frameworks for reliable, high-quality outputs." },
      { week: "Week 3", topic: "AI for Content & Research", details: "Writing, summarising, image generation, research workflows." },
      { week: "Week 4", topic: "No-Code Automation", details: "Zapier / Make basics — triggers, actions, filters." },
      { week: "Week 5", topic: "AI + Automation", details: "Auto-reply bots, lead capture, content pipelines." },
      { week: "Week 6", topic: "Chatbots & Agents", details: "Build a support / sales chatbot for a website or WhatsApp." },
      { week: "Week 7", topic: "Business Use-Cases", details: "Real client scenarios: sales, admin, marketing." },
      { week: "Week 8", topic: "Capstone", details: "Ship a real AI-powered workflow end-to-end." },
    ],
    projects: [
      "Auto-generated weekly content calendar",
      "WhatsApp AI auto-reply bot for a small business",
      "AI-powered lead qualification flow",
      "Custom GPT / assistant for a niche",
    ],
    careers: [
      { role: "AI / Automation Specialist", salary: "₦300,000 – ₦900,000 / month" },
      { role: "AI Consultant (Freelance)", salary: "$30 – $120 / hour" },
      { role: "Content / Marketing Automation Lead", salary: "₦250,000 – ₦700,000 / month" },
    ],
    certification: "AI & Automation Certificate + real deployed automation in your portfolio.",
    faqs: [
      { q: "Do I need to know programming?", a: "No — this track is mostly no-code and prompt-based, though Python helps if you want to go deeper later." },
      { q: "Which AI tools do you cover?", a: "ChatGPT, Claude, Gemini, image/video AI tools, plus Zapier, Make and n8n for automation." },
    ],
    related: ["python-programming", "data-analysis", "ui-ux-video"],
  },
  {
    slug: "cyber-security",
    name: "Cyber Security",
    tagline: "Practical cyber security — protect people, businesses and yourself online.",
    icon: "ti-shield-lock",
    iconBg: "rgba(163,45,45,0.15)",
    iconColor: "#FF7070",
    overview:
      "A practical introduction to cyber security. Learn how attackers think, how systems get compromised, and how to defend networks, accounts and data. Every module is hands-on in a safe lab environment.",
    objectives: [
      "Understand the modern threat landscape",
      "Practise network security fundamentals",
      "Detect and respond to common attacks (phishing, malware, weak passwords)",
      "Use encryption and secure authentication properly",
      "Apply security best practices for individuals and small businesses",
    ],
    duration: "3 months",
    format: "Hybrid — physical + live online",
    level: "Beginner to Intermediate",
    price: "₦30,000 / month",
    installment: "Split payment available",
    curriculum: [
      { week: "Week 1", topic: "Security Foundations", details: "CIA triad, threats, vulnerabilities, risk." },
      { week: "Week 2", topic: "Networking Basics", details: "IP, DNS, HTTP/HTTPS, firewalls." },
      { week: "Week 3", topic: "Passwords & MFA", details: "Password managers, 2FA, credential hygiene." },
      { week: "Week 4", topic: "Phishing & Social Engineering", details: "Recognise, simulate and defend against attacks." },
      { week: "Week 5", topic: "Malware & Endpoint Security", details: "Types of malware, AV, safe browsing, updates." },
      { week: "Week 6", topic: "Encryption", details: "Symmetric/asymmetric, HTTPS, VPNs." },
      { week: "Week 7", topic: "Incident Response Basics", details: "What to do when something breaks." },
      { week: "Week 8", topic: "Small Business Security", details: "Practical playbook for real businesses." },
    ],
    projects: [
      "Personal security audit and hardening plan",
      "Phishing simulation report",
      "Small business security policy document",
      "Home network hardening lab",
    ],
    careers: [
      { role: "Junior Security Analyst", salary: "₦250,000 – ₦700,000 / month" },
      { role: "IT Security Officer", salary: "₦300,000 – ₦900,000 / month" },
      { role: "Freelance Security Consultant (SME)", salary: "₦150,000 – ₦800,000 / engagement" },
    ],
    certification:
      "Glass Nexus Academy Cyber Security Certificate + preparation guidance for global certifications (CompTIA Security+, ISC2 CC).",
    faqs: [
      { q: "Is this course legal / ethical?", a: "Yes. Everything is taught in a lab environment for defensive purposes. We take ethics seriously." },
      { q: "Do I need a strong tech background?", a: "Basic computer literacy is enough. We build the networking and OS fundamentals from scratch." },
    ],
    related: ["web-design-backend", "ai-automation", "hardware-repairs"],
  },
  {
    slug: "ui-ux-video",
    name: "UI/UX Design & Video Editing",
    tagline: "Design beautiful interfaces in Figma and edit polished video content.",
    icon: "ti-palette",
    iconBg: "rgba(255,140,66,0.15)",
    iconColor: "#FF8C42",
    overview:
      "A combined creative track. Learn to design clean, user-friendly interfaces in Figma and to edit professional video content for YouTube, social media and brands — two of today's most in-demand freelance skills.",
    objectives: [
      "Apply core UI/UX principles: hierarchy, contrast, usability",
      "Design responsive screens and prototypes in Figma",
      "Edit videos in Premiere Pro / CapCut with clean cuts and transitions",
      "Use motion, sound and text overlays for engagement",
      "Deliver work that clients actually want to pay for",
    ],
    duration: "3 months",
    format: "Hybrid — physical + live online",
    level: "Beginner-friendly",
    price: "₦25,000 / month",
    installment: "Split payment available",
    curriculum: [
      { week: "Week 1", topic: "Design Thinking", details: "Users, problems, empathy, wireframing basics." },
      { week: "Week 2", topic: "Figma Foundations", details: "Frames, components, auto layout." },
      { week: "Week 3", topic: "UI Systems", details: "Colour, type, spacing, design tokens." },
      { week: "Week 4", topic: "Prototyping", details: "Interactive prototypes, user testing basics." },
      { week: "Week 5", topic: "Video Editing Basics", details: "Cuts, timeline, audio, exports." },
      { week: "Week 6", topic: "Motion & Effects", details: "Transitions, text animation, colour grading." },
      { week: "Week 7", topic: "Content for Social", details: "Reels, shorts, TikTok formats." },
      { week: "Week 8", topic: "Client-style Project", details: "Full brand deliverable — UI + promo video." },
    ],
    projects: [
      "Mobile app UI in Figma",
      "Landing page redesign",
      "30–60s brand promo video",
      "Full social media reel pack",
    ],
    careers: [
      { role: "UI/UX Designer", salary: "₦250,000 – ₦700,000 / month" },
      { role: "Video Editor (Agency)", salary: "₦200,000 – ₦600,000 / month" },
      { role: "Freelance Creator", salary: "₦50,000 – ₦500,000 / project" },
    ],
    certification: "UI/UX + Video Editing Certificate with a delivered brand-style project.",
    faqs: [
      { q: "Do I need to be artistic already?", a: "No — we teach principles. Consistency and clarity matter more than raw art skill." },
      { q: "Which video software do you use?", a: "Adobe Premiere Pro on desktop and CapCut on mobile — the two most in demand right now." },
    ],
    related: ["web-design-frontend", "ai-automation", "computer-operations"],
  },
];

export function getCourse(slug: string) {
  return COURSES.find((c) => c.slug === slug);
}
